KSP-RO/RealPlume-StockConfigs

GameData/RealPlume-Stock/AB_Launchers/ABL_Nose_A.cfg
GameData/RealPlume-Stock/TantaresLV/PLV_Engine_B.cfg
GameData/RealPlume-Stock/TantaresLV/TLV_LES_A.cfg
GameData/RealPlume-Stock/TundraExploration/Engine1.cfg
GameData/RealPlume-Stock/TundraExploration/Engine2.cfg
GameData/RealPlume-Stock/TundraExploration/Ladee_Engine.cfg
GameData/RealPlume-Stock/TundraExploration/Rodan.cfg

Updated AB Launchers and TantaresLV configs to work with the updated plumes. Also added Tundra Exploration configs. (Last configs from me for a while, need to actually play the game)

Tundra Exploration and Updates.

---

GameData/RealPlume-Stock/TundraExploration/Engine1.cfg
GameData/RealPlume-Stock/TundraExploration/Engine2.cfg

I extended the plumes on the Falcon 9 as they seemed a bit too short. (Am I doing too much with this?)

Updated Tundra Exploration configs

---

GameData/RealPlume-Stock/Atomic Age/NuclearJetEngine.cfg
GameData/RealPlume-Stock/Atomic Age/nuclearEngineKANDL.cfg
GameData/RealPlume-Stock/Atomic Age/nuclearEngineLANTR.cfg
GameData/RealPlume-Stock/Atomic Age/nuclearEngineLightbulb.cfg
GameData/RealPlume-Stock/ModRocketSys/NB0mLFOengine1.cfg
GameData/RealPlume-Stock/ModRocketSys/NB0mMonoEngine1.cfg
GameData/RealPlume-Stock/ModRocketSys/NB2mNuclearEngine.cfg
GameData/RealPlume-Stock/ModRocketSys/NB3mHoundEngine.cfg
GameData/RealPlume-Stock/ModRocketSys/NB3mQuadEngine.cfg
GameData/RealPlume-Stock/ModRocketSys/NBLAStower.cfg
GameData/RealPlume-Stock/ModRocketSys/NBflingatron.cfg
GameData/RealPlume-Stock/ModRocketSys/NBjetBasic0m.cfg
GameData/RealPlume-Stock/ModRocketSys/NBjetTurbo0m.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYdecouplerRadial1.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYdecouplerRadial2.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYejectatron.cfg

Added Modular Rocket Systems and Atomic Age support, finished SpaceY configs.

Modular Rocket Systems, Atomic Age, Space Y

---

GameData/RealPlume-Stock/TantaresLV/TLV_Engine_A.cfg

Plume was only applying to the first engine mode, this should fix that.

Fixed TLV_Engine_A config

---

GameData/RealPlume-Stock/BTSM/BTSMLiquidEngine1-2.cfg
GameData/RealPlume-Stock/BTSM/BTSMLiquidEngine1.cfg
GameData/RealPlume-Stock/BTSM/BTSMLiquidEngine3.cfg
GameData/RealPlume-Stock/BTSM/BTSMSolidRocket1.cfg
GameData/RealPlume-Stock/BTSM/BTSMSolidRocket2.cfg

Support for the BTSM mod, created by Avera9eJoe on the forums. Submitting for him.

Adding the BTSM support

---

Space Shuttle/OMS.cfg
Space Shuttle/SRB.cfg
Space Shuttle/SSME HL.cfg

It was more difficult to reach this point that to create the config... :-)))))

Space Shuttle program mod config.

---

GameData/RealPlume-Stock/CTN/sem24Booser.cfg
GameData/RealPlume-Stock/CTN/sm25Booster.cfg

Another new mod that I'm using, another set of configs!

Phoenix Industries: Boosters (CTN) configs

---

GameData/RealPlume-Stock/CTN/sem24Booser.cfg

Mod just updated with changes to model orientation which broke original
configs.

Fix for Phoenix Boosters

---

GameData/RealPlume-Stock/TantaresLV/TUS_Engine_A.cfg

Updated configs to add the latest engine

Updated TantaresLV configs

---

GameData/RealPlume-Stock/DIRECT_LV/DIRECT_RS25.cfg
GameData/RealPlume-Stock/DIRECT_LV/DirectSRBX.cfg
GameData/RealPlume-Stock/DIRECT_LV/directCone.cfg

DIRECT LV configs

---

GameData/RealPlume-Stock/PlanetaryBaseInc/KKAOSS_engine_g.cfg

KPBS Configs

---

GameData/RealPlume-Stock/KOSMOS/KOSMOS.cfg

Plume configuration and positional fixes

No mr bond add kosmos engines

---

GameData/RealPlume-Stock/KSO/boosterkso.cfg
GameData/RealPlume-Stock/KSO/omskso.cfg
GameData/RealPlume-Stock/KSO/super25boosterkso.cfg
GameData/RealPlume-Stock/KSO/super25enginekso.cfg
GameData/RealPlume-Stock/KSO/thrustmaxkso.cfg

Configs for both shuttles from the Kerbin Shuttle Orbiter System mod

Kerbin Shuttle Orbiter System Configs

---

GameData/RealPlume-Stock/Tantares/Agena_Control_A.cfg
GameData/RealPlume-Stock/Tantares/Alnair_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Alnair_LES_A.cfg
GameData/RealPlume-Stock/Tantares/Alnair_LK_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Alto_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Capella_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Castor_LM_Engine.cfg
GameData/RealPlume-Stock/Tantares/Castor_Nerva.cfg
GameData/RealPlume-Stock/Tantares/Libra_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Libra_Engine_B.cfg
GameData/RealPlume-Stock/Tantares/Libra_Nesting_A.cfg
GameData/RealPlume-Stock/Tantares/Phoenix_Ex_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Polaris_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Pollux_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Tantares_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Tantares_Engine_B.cfg
GameData/RealPlume-Stock/Tantares/Vega_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Vega_Engine_B.cfg
GameData/RealPlume-Stock/Tantares/Vega_Engine_C.cfg
GameData/RealPlume-Stock/Tantares/Vostok_Engine_A.cfg

Updated and reworked configs for Tantares. Now applies to all engines accurate to the engines they are based off.

Updated Tantares Configs

---

GameData/RealPlume-Stock/BahamutoD/bahars68b.cfg
GameData/RealPlume-Stock/BahamutoD/constellationBNTR.cfg

* Add stock RealPlume support for the BahamutoD Constellation Essentials engines.

RPS Constellation Essentials

---

GameData/RealPlume-Stock/SpaceY-Lifters/SYSRB_0625L5.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYSRB_0625L6R.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYSRB_0625L9.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYSRB_1875L.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYSRB_1875S.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYSRB_1875X.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYSRB_25L.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYSRB_25S.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYSRB_25X23.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYSRB_375L08.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYSRB_375L12.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYSRB_375L21.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYSRBradial01.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYdecouplerRadial1.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYdecouplerRadial2.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYengine1mK1.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYengine2mM1.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYengine2mR1.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYengine5mM5.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYengine5mM9.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYengine5mR5.cfg
GameData/RealPlume-Stock/SpaceY-Lifters/SYengine5mR7.cfg

Noticed some problems with SpaceY plumes, with some appearing a bit away from the nozzle, and some that were too small.

Updated SpaceY configs

---

GameData/RealPlume-Stock/PlanetaryBaseInc/KKAOSS_engine_g.cfg
GameData/RealPlume-Stock/RLA_Stockalike/RLA_mp_medium_vac.cfg
GameData/RealPlume-Stock/RLA_Stockalike/RLA_mp_small_radial.cfg
GameData/RealPlume-Stock/RLA_Stockalike/RLA_mp_small_stack.cfg
GameData/RealPlume-Stock/RLA_Stockalike/RLA_mp_tiny_stack.cfg
GameData/RealPlume-Stock/Squad/liquidEngine22.cfg
GameData/RealPlume-Stock/Squad/liquidEngine3.cfg
GameData/RealPlume-Stock/Squad/liquidEngineMini.cfg
GameData/RealPlume-Stock/Tantares/Capella_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Castor_LM_Engine.cfg
GameData/RealPlume-Stock/Tantares/Libra_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Phoenix_Ex_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Pollux_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Tantares_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Tantares_Engine_B.cfg
GameData/RealPlume-Stock/Tantares/Vega_Engine_A.cfg
GameData/RealPlume-Stock/Tantares/Vega_Engine_B.cfg
GameData/RealPlume-Stock/Tantares/Vega_Engine_C.cfg
GameData/RealPlume-Stock/Tantares/Vostok_Engine_A.cfg
GameData/RealPlume-Stock/TantaresLV/TUS_Engine_A.cfg

Temporarily broke support for VSR, will fix after VSR release for 1.1

Updated for newest RealPlume

---

GameData/RealPlume-Stock/AIES/enginelmodc.cfg
GameData/RealPlume-Stock/AIES/microEngineex1sat.cfg
GameData/RealPlume-Stock/BTSM/BTSMLiquidEngine3.cfg
GameData/RealPlume-Stock/FASA/FASAAgena_Engine.cfg
GameData/RealPlume-Stock/FASA/FASAAgena_Engine_FP.cfg
GameData/RealPlume-Stock/FASA/FASAApolloAPS.cfg
GameData/RealPlume-Stock/FASA/FASAGeminiEngineFuel.cfg
GameData/RealPlume-Stock/FASA/FASAGeminiLFECentarTwin.cfg
GameData/RealPlume-Stock/FASA/FASALM_AscentEngine.cfg
GameData/RealPlume-Stock/FASA/FASALM_DescentEngine.cfg
GameData/RealPlume-Stock/FASA/FASAPioneerLFE.cfg
GameData/RealPlume-Stock/FASA/FASA_Gemini_Lander_Eng.cfg
GameData/RealPlume-Stock/FASA/FASA_Mercury_LFEng.cfg
GameData/RealPlume-Stock/KOSMOS/KOSMOS.cfg
GameData/RealPlume-Stock/KSO/omskso.cfg
GameData/RealPlume-Stock/ModRocketSys/NB0mMonoEngine1.cfg
GameData/RealPlume-Stock/ModRocketSys/NB3mHoundEngine.cfg
GameData/RealPlume-Stock/RSCapsuledyne/TaurusOrbitalEngine.cfg
GameData/RealPlume-Stock/SXT/MEMDescentMod.cfg
GameData/RealPlume-Stock/SXT/MEMLander.cfg
GameData/RealPlume-Stock/SXT/SXTKOPO4E.cfg
GameData/RealPlume-Stock/Space Shuttle/OMS.cfg
GameData/RealPlume-Stock/TundraExploration/Ladee_Engine.cfg

Updates remaining plumes to latest RealPlume

Update remaining plumes

---

GameData/RealPlume-Stock/Squad/omsEngine.cfg
GameData/RealPlume-Stock/Tantares/Alto_Engine_B.cfg
GameData/RealPlume-Stock/TantaresLV/TLV_Vernier.cfg

Only covers 1 stock, 2 Tantares, and 1 TantaresLV engines for now.

Added plumes to some physicsless parts

---

GameData/RealPlume-Stock/HGR/HGR_FG90_Engine.cfg

Accidentally misentered a number which would cause the game to not load... sorry!

Fix game breaking error

---

GameData/RealPlume-Stock/TundraExploration/Rosetta_Engine.cfg

Updated TundraExploration configs for TundraExploration 0.8.5

Updated TundraExploration configs

---

GameData/RealPlume-Stock/SDHI/SDHI_2.5_Mk1-2AeroShroud.cfg
GameData/RealPlume-Stock/SDHI/SDHI_LES.cfg

Configs to support SDHI v3.1.1

SDHI configs

---

GameData/RealPlume-Stock/HGR/HGRG47b.cfg

This guy went out whack recently for some reason.

Update G47b plume for HGR

---

GameData/RealPlume-Stock/Space Launch System/AJ10-190.cfg
GameData/RealPlume-Stock/Space Launch System/AJ1E6.cfg
GameData/RealPlume-Stock/Space Launch System/DarkKnight.cfg
GameData/RealPlume-Stock/Space Launch System/F1B.cfg
GameData/RealPlume-Stock/Space Launch System/R4D11.cfg
GameData/RealPlume-Stock/Space Launch System/RL-10B2.cfg
GameData/RealPlume-Stock/Space Launch System/RL-10C2.cfg
GameData/RealPlume-Stock/Space Launch System/RS-25.cfg
GameData/RealPlume-Stock/Space Launch System/SEPengine.cfg
GameData/RealPlume-Stock/Space Launch System/SLSSolidRocket.cfg
GameData/RealPlume-Stock/Space Launch System/Separatron1.cfg
GameData/RealPlume-Stock/Space Launch System/Separatron3.cfg

Adding configs for compatibility between RealPlume and Space Launch System Stock version.

Space Launch System support

---

GameData/RealPlume-Stock/KerbalStockLauncherOverhaul/KE180.cfg
GameData/RealPlume-Stock/KerbalStockLauncherOverhaul/KE4.cfg
GameData/RealPlume-Stock/KerbalStockLauncherOverhaul/KE68.cfg
GameData/RealPlume-Stock/KerbalStockLauncherOverhaul/LVT1C.cfg
GameData/RealPlume-Stock/KerbalStockLauncherOverhaul/LVT1D.cfg
GameData/RealPlume-Stock/KerbalStockLauncherOverhaul/LVTA.cfg
GameData/RealPlume-Stock/KerbalStockLauncherOverhaul/RTA.cfg
GameData/RealPlume-Stock/KerbalStockLauncherOverhaul/sepratronx.cfg

Kerbal Stock Launcher Overhaul configs

KSLO Configs

---

GameData/RealPlume-Stock/PartOverhauls/liquidEngine303.cfg
GameData/RealPlume-Stock/PartOverhauls/liquidEngine909.cfg
GameData/RealPlume-Stock/PartOverhauls/liquidEngineT15.cfg
GameData/RealPlume-Stock/PartOverhauls/liquidEngineT30.cfg
GameData/RealPlume-Stock/PartOverhauls/liquidEngineT45.cfg

Configs to support the revamped parts released along with the 1.2 prerelease. (Configs could be better, fuel type determined from best match to IRL engines)

Porkjet Part Overhaul Configs

---

GameData/RealPlume-Stock/KWCommunityFixes/KW2mengineSPSB.cfg
GameData/RealPlume-Stock/KWRocketry/KW3mengineWildcatXR.cfg
GameData/RealPlume-Stock/NearFutureSpacecraft/orbitalEngine-0625.cfg
GameData/RealPlume-Stock/NearFutureSpacecraft/orbitalEngine-25.cfg
GameData/RealPlume-Stock/NearFutureSpacecraft/orbitalEngine-375.cfg

Added configs for Near Future's LFO engines.

Near Future LFO Engines

---

GameData/RealPlume-Stock/KWCommunityFixes/KW2mengineSPSB.cfg
GameData/RealPlume-Stock/KWRocketry/KW3mengineWildcatXR.cfg

Added config for the LFO service engine added by KWCommunityFixes and fixed the typo in the Wildcat-XR config.

Added LFO Service Propulsion config and fixed typo for Wildcat-XR

---

GameData/RealPlume-Stock/RealScaleBoosters/RSBengineAJ10-118K.cfg
GameData/RealPlume-Stock/RealScaleBoosters/RSBengineCastor120.cfg
GameData/RealPlume-Stock/RealScaleBoosters/RSBengineCastor30.cfg
GameData/RealPlume-Stock/RealScaleBoosters/RSBengineHM7B.cfg
GameData/RealPlume-Stock/RealScaleBoosters/RSBengineJ2.cfg
GameData/RealPlume-Stock/RealScaleBoosters/RSBengineRL10A42.cfg
GameData/RealPlume-Stock/RealScaleBoosters/RSBengineRL10B2.cfg
GameData/RealPlume-Stock/RealScaleBoosters/RSBengineRS25.cfg
GameData/RealPlume-Stock/RealScaleBoosters/RSBengineRS27A.cfg
GameData/RealPlume-Stock/RealScaleBoosters/RSBengineVulcain2.cfg

Fixed some engines and added a few new ones

fixes and new engines for RealScaleBoosters

---

GameData/RealPlume-Stock/NewTantaresLV/LLV_A_Engine_1.cfg
GameData/RealPlume-Stock/NewTantaresLV/LLV_B_Engine_1.cfg
GameData/RealPlume-Stock/NewTantaresLV/LLV_G_Engine_1.cfg
GameData/RealPlume-Stock/NewTantaresLV/LLV_V_Engine_1.cfg
GameData/RealPlume-Stock/NewTantaresLV/SUS_Engine_1.cfg
GameData/RealPlume-Stock/NewTantaresLV/TUS_Engine_1.cfg

New configs (In a new folder) for the new version of TantaresLV

New TantaresLV Configs

---

GameData/RealPlume-Stock/NewTantares/Libra_Engine_1.cfg
GameData/RealPlume-Stock/NewTantares/Libra_Nesting_1.cfg
GameData/RealPlume-Stock/NewTantares/Tantares_Engine_1.cfg
GameData/RealPlume-Stock/NewTantares/Tantares_Engine_2.cfg

New folder to separate from old Tantares

Added NewTantares Configs

---

GameData/RealPlume-Stock/NewTantares/Eridani_Engine_1.cfg

Added the latest prerelease engine, uses the new config structure

Updated NewTantares

---

RealPlume-StockConfigs.netkan

According to forum thread and spacedock page, the last release still works in 1.3

update netkan file for 1.3

---

GameData/RealPlume-Stock/SXT Continued/SXTnuclearramjet.cfg
GameData/RealPlume-Stock/Taerobee/Aerobee_Jr.cfg
GameData/RealPlume-Stock/Taerobee/Little_Leo.cfg

Fix patches with more than one pass specified

---

GameData/RealPlume-Stock/MissingHistory/liquidEngineLV-303.cfg
GameData/RealPlume-Stock/MissingHistory/liquidEngineLV-909.cfg
GameData/RealPlume-Stock/MissingHistory/liquidEngineLV-T15.cfg
GameData/RealPlume-Stock/MissingHistory/liquidEngineLV-T30.cfg
GameData/RealPlume-Stock/MissingHistory/liquidEngineLV-T45.cfg
GameData/RealPlume-Stock/Squad/liquidEngine.cfg
GameData/RealPlume-Stock/Squad/liquidEngine2-2_v2.cfg
GameData/RealPlume-Stock/Squad/liquidEngine2.cfg
GameData/RealPlume-Stock/Squad/liquidEngine3_v2.cfg
GameData/RealPlume-Stock/Squad/liquidEngineMini_v2.cfg
GameData/RealPlume-Stock/SquadExpansion/LiquidEngineKE-1.cfg
GameData/RealPlume-Stock/SquadExpansion/LiquidEngineLV-T91.cfg
GameData/RealPlume-Stock/SquadExpansion/LiquidEngineLV-TX87.cfg
GameData/RealPlume-Stock/SquadExpansion/LiquidEngineRE-I2.cfg
GameData/RealPlume-Stock/SquadExpansion/LiquidEngineRK-7.cfg
GameData/RealPlume-Stock/VenStockRevamp/S2ServiceEngine.cfg
GameData/RealPlume-Stock/VenStockRevamp/engineLargeSkipper.cfg
GameData/RealPlume-Stock/VenStockRevamp/liquidEngine.cfg
GameData/RealPlume-Stock/VenStockRevamp/liquidEngine2.cfg
GameData/RealPlume-Stock/VenStockRevamp/nuclearengine.cfg
GameData/RealPlume-Stock/VenStockRevamp/size2nuclearEngine.cfg

Added CFG files for Poodle, Spark and Terrier engines, which have been redesigned in 1.6

Added CFG files for Poodle, Spark and Terrier engines

---

GameData/RealPlume-Stock/Squad/liquidEngineAerospike.cfg
GameData/RealPlume-Stock/SquadExpansion/LiquidEngineKE-1.cfg
GameData/RealPlume-Stock/SquadExpansion/LiquidEngineLV-TX87.cfg
RealPlume-StockConfigs.netkan

Updates for KE-1, LV-TX87, and Aerospike
